version: '2'

services:
  dev:
    build:
      context: .
    volumes:
      - ./database:/wordpress/wp-content/database
      - ./uploads:/wordpress/wp-content/uploads
      - ./plugins:/wordpress/wp-content/plugins
      - ./themes:/wordpress/wp-content/themes
      - ./wp-config.php:/wordpress/wp-config.php
      - ./php.ini:/usr/local/etc/php/php.ini
    restart: always
    entrypoint: sh -c "cd wordpress && php -S 0.0.0.0:8000"
    ports:
      - "${RHPORT}:8000"
    user: ${CURRENT_UID}
